# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
knowledge_base:
  linked_repositories:
    - repository: dhaiducek/startrhacm
      instructions: Wrapper script to provision an Openshift cluster and install Red Hat Advanced Cluster Management for Kubernetes (RHACM).
    - repository: openshift/hive
      instructions: The controller and API for ClusterPools and ClusterClaims to provision Openshift clusters from cloud providers.
