name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck against scripts
        run: find . -name "*.sh" -exec shellcheck {} +
